# Site
name: "Zhang Tao lab"
title: "Zhang Tao lab"
description: "Bioinformatics, Epigenetics and Genomics."
meta_description: "Bioinformatics, Epigenetics and Genomics."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 6
baseurl: 'http://zhangtaolab.org'
email: 'contact@zhangtaolab.org'
disqus: ''
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  han_ys:
    name: Han Yangshuo
    display_name: Han Yangshuo
    email: hanyangshuo@zhangtaolab.org
    description: "This is a description."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge